# docker-compose.yml
services:

  fd2_drift_generator:
    image: fd2_drift_generator_img
    build: 
      context: .
      dockerfile: /docker/Dockerfile
    container_name: fd2_drift_generator
    env_file:  
      - ./app/.env
    volumes:
      - ./app:/home/app  
    working_dir: /home/app
    command: python fd2_drift_report_generator.py
    # ports:
      # - "8005:8005"  # host:container 
