services:
  modelizer:
    image: modelizer_img
    # build: /docker
    # build:
      # context: ./modelizer/docker         # relative to the location of the docker-compose.yml file
      # dockerfile: Dockerfile              # If the Dockerfile is called something other than 'Dockerfile'
    container_name: modelizer
    environment:
      - AWS_REGION=${AWS_REGION}  
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}  
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PORT=${PORT}                        # communication consumer <-> modelizer
    volumes:
      # - ./app:/home/app
      - ../../../01_model_and_data/01_model_and_data_ops/05_modelizer/app:/home/app                 
    working_dir: /home/app                            
    command: python modelizer04.py
    ports:
      - "${PORT}:${PORT}"                   # host:container
    networks:
      - consumer-modelizer

  consumer:
    image: consumer_img
    # build: /docker
    container_name: consumer
    environment:
      - SASL_USERNAME=${SASL_USERNAME}
      - SASL_PASSWORD=${SASL_PASSWORD}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT}
      - PORT=${PORT}                        # for communication consumer <-> modelizer 
    volumes:
      - ./app:/home/app
    working_dir: /home/app
    command: python consumer06.py
    networks:
      - consumer-modelizer

networks:
  consumer-modelizer:
    driver: bridge



