# docker-compose.yml

services:
  greet:
    image: greet_img
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: greet
    environment:
      - PASSWORD=${PASSWORD}
    volumes:
      - ./app:/home/app
      - ./img:/home/img
    
    # Specifies the default working directory in the container at the time of service execution
    # ie independently of the WORKDIR directive defined in the Dockerfile
    working_dir: /home/app
    command: python main.py


