# docker-compose.yml

services:
  greet:
    image: greet_img
    build: 
      context: .
      dockerfile: docker/Dockerfile
      args:
        REQUIREMENTS_FILE: requirements.txt
    container_name: greet
    environment:
      - PASSWORD=${PASSWORD}
    volumes:
      - ./app:/home/app
      - ./img:/home/img
    working_dir: /home/app
    command: python main.py

  greet_test:
      image: greet_img_test
      build: 
        context: .
        dockerfile: docker/Dockerfile
        args:
          REQUIREMENTS_FILE: requirements_test.txt
      container_name: greet_test
      environment:
        - PASSWORD=${PASSWORD}
      volumes:
        - ./app:/home/app
        - ./img:/home/img
      working_dir: /home
      command: pytest
