# docker-compose-test.yml

services:
  greet_test:
    image: greet_img_test
    container_name: greet_test
    environment:
      - PASSWORD=${PASSWORD}
    volumes:
      - ./app:/home/app
      - ./img:/home/img

    # Specifies the default working directory in the container at the time of service execution
    # ie independently of the WORKDIR directive defined in the Dockerfile
    working_dir: /home
    command: pytest


